version: "3"

services:
  # caddy-gen service
  caddy-gen:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: caddy-gen
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./output:/data
    environment:
      - CADDY_GEN_NETWORK=gateway
      - CADDY_GEN_OUTFILE=/data/docker-sites.caddy
    networks:
      - gateway

  # Test service 1 - Simple Nginx website
  web1:
    image: nginx:alpine
    container_name: web1
    restart: unless-stopped
    volumes:
      - ./web1:/usr/share/nginx/html
    labels:
      virtual.bind: 80 web1.local
    networks:
      - gateway

  # Test service 2 - Nginx website with path
  web2:
    image: nginx:alpine
    container_name: web2
    restart: unless-stopped
    volumes:
      - ./web2:/usr/share/nginx/html
    labels:
      virtual.bind: /api 80 web2.local | header Server "My Custom Server"
    networks:
      - gateway

  # Test service 3 - Nginx website with multiple hostnames and directives
  web3:
    image: nginx:alpine
    container_name: web3
    restart: unless-stopped
    volumes:
      - ./web3:/usr/share/nginx/html
    labels:
      virtual.bind: 80 web3.local www.web3.local | host:tls internal | header Strict-Transport-Security "max-age=31536000"
    networks:
      - gateway

volumes:
  caddy_data:
  caddy_config:

networks:
  gateway:
    name: gateway
    driver: bridge
